# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e40f5b2f422568330b55844e08c4fa186c0a467309b3874b2af6c5a53fdcf27f0f325d209474282b6403d5f23a71f1f941dfbb6373422cc6e9fe002dfbf19329

test:
  secret_key_base: 7ebd3a42db553ce6d5eca444688898c83636d6f52a272c25780d1c56f7b369644a006225bd30944c59aa9045a1bf3a13cf3f0bcf5240571ff756899efdc0100e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
